name: Roman Mokrzan
title: Roman Mokrzan | Android Java Kotlin programowanie
description: Technicznie. O programowaniu. Głównie o Androidzie.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: romanmokrzan@gmail.com
disqus_username: romanmokrzan
show_hero: true
