name: Roman Mokrzan
title: Roman Mokrzan | Android Java Kotlin programowanie
description: Technicznie o programowaniu. Głównie o Androidzie. Trochę luźnych myśli na inne tematy.
tags:
  - blog
  - template
  - jekyll
  - theme
  - netlify
email: romanmokrzan@gmail.com
#disqus_username: disqus_username
show_hero: true
